services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch

    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana

    ports:
      - "5601:5601"

    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200

    depends_on:
      - elasticsearch

  postgres:
    image: postgres:13
    container_name: airflow_postgres

    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

    ports:
      - "5432:5432"

  airflow-webserver:
    image: apache/airflow:2.8.1
    container_name: airflow_webserver

    depends_on:
      - postgres

    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow_postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=mysecretkey

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data

    ports:
      - "8080:8080"

    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.8.1
    container_name: airflow_scheduler

    depends_on:
      - postgres

    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow_postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=mysecretkey

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data

    command: scheduler